image: openbsd/7.3
packages:
  - go
  - git
secrets:
  - 9ef6e07e-cae5-4ec0-b799-8898de1f742b
sources:
  - ssh://git@git.sr.ht/~aqtrans/jasper
tasks:
  - setup: |
      cd jasper
      go get -d
      go generate
  - test: |
      cd jasper
      go test
      go test -race
      go test -cover
      go test -bench=.
  - build: |
      cd jasper
      go build -ldflags "-X main.sha1ver=$(git rev-parse HEAD) -X main.buildTime=$(date +'%Y-%m-%d_%T')" -o jasper
  - deploy: |
      cd jasper
      scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no jasper deploy@starbuck.squanch.space:/tmp/jasper
      ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no deploy@starbuck.squanch.space "doas /bin/mv /tmp/jasper /usr/local/bin/jasper"
      ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no deploy@starbuck.squanch.space "doas /usr/sbin/rcctl restart jasper"
