image: openbsd/7.6
packages:
  - go
  - git
secrets:
  - 9ef6e07e-cae5-4ec0-b799-8898de1f742b
sources:
#  - ssh://git@git.sr.ht/~aqtrans/jasper
  - ssh://git@git.jba.io/go/jasper.git
environment:
  project: jasper
  remote: deploy@barry.squanch.space
triggers:
  - action: email
    condition: failure
    to: Jordan Anderson <jordan@jba.io>
tasks:
  - setup: |
      cd ${project}
      go get -d
      go generate
  - test: |
      cd ${project}
      go test
      go test -race
      go test -cover
      go test -bench=.
  - build: |
      cd ${project}
      go build -ldflags "-X main.sha1ver=$(git rev-parse HEAD) -X main.buildTime=$(date +'%Y-%m-%d_%T')" -o jasper
      if [ "$(git rev-parse origin/master)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
  - deploy: |
      cd ${project}
      scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no jasper $remote:/tmp/jasper
      ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $remote "doas /bin/mv /tmp/jasper /usr/local/bin/jasper"
      ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $remote "doas /usr/sbin/rcctl restart jasper"
