kind: pipeline
name: jasper

steps:
- name: get deps
  image: golang
  volumes:
    - name: deps
      path: /go
  commands:
    - go get -d
    - go generate ./...    

- name: test
  image: golang
  volumes:
    - name: deps
      path: /go
  commands:
    - go test
    - go test -race
    - go test -cover
    - go test -bench=.    

- name: build
  image: golang
  volumes:
    - name: deps
      path: /go
  commands:
    - go build

- name: package
  pull: never
  image: deb-pkg
  commands: 
    - dch -M -v 1.0-$DRONE_COMMIT_BRANCH-$DRONE_BUILD_NUMBER "New version from Git" && dch -M -r -D buster ""
    - debuild -us -uc -b  
    - mv ../jasper_*.deb jasper.deb

- name: deploy
  image: alpine
  environment:
    SSH_KEY:
      from_secret: ssh_key
    DEPLOY_HOST: 'deploy@bob.jba.io'
  commands:
  - mkdir $HOME/.ssh
  - echo "$SSH_KEY" > $HOME/.ssh/id_ed25519
  - cat $HOME/.ssh/id_ed25519
  - chmod 600 $HOME/.ssh/id_ed25519
  - apk add --no-cache openssh
  - ssh-keyscan -H bob.jba.io > $HOME/.ssh/known_hosts
  - scp jasper.deb $DEPLOY_HOST:/home/deploy/
  - ssh $DEPLOY_HOST sudo dpkg -i jasper.deb

- name: notify
  image: plugins/matrix
  settings:
    homeserver: https://squanch.space
    roomid: WJRHcFjDqYlolDerNY:squanch.space
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password

volumes:
  - name: deps
    temp: {}  