image: golang:latest

cache:
  key: "$CI_BUILD_REF_NAME"
  paths:
    - vendor/

before_script:
  - ln -s /builds /go/src/jba.io
  - cd /go/src/jba.io/go/jasper
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'

stages:
  - install-environment
  - build
  - test
  - deploy  

install-go:
  stage: install-environment
  script:
    - go version
    - echo $PATH
    - echo $GOPATH
    - go env
    - which go

build-my-project:
  stage: build
  script:
    - go get -u github.com/kardianos/govendor
    - govendor sync
    - go get -d
    - go build -o ./jasper
  artifacts:
    paths:
      - jasper
      - vendor/

test-my-project:
  stage: test
  coverage: '/coverage: \d+\.\d+/'
  script:
    - go get -d  
    - go test -v
    - go test -race
    - go test -cover

deploy_staging:
  stage: deploy
  script:
    - apt-get update -y && apt-get install -y rsync
    - /bin/bash ./deploy.sh golang@leela.es.gy golang@$CI_PROJECT_NAME $CI_PROJECT_NAME
  environment:
    name: staging
    url: http://jasper.leela.es.gy
  when: manual

deploy_prod:
  stage: deploy
  script:
    - apt-get update -y && apt-get install -y rsync
    - /bin/sh ./deploy.sh golang@frink.es.gy golang@$CI_PROJECT_NAME $CI_PROJECT_NAME
  environment:
    name: production
    url: https://thatsapaddl.in
  only:
    - master
