#!/bin/sh

set -e

USER=jasper

if ! getent passwd "$USER" >/dev/null; then
  adduser --quiet --system --home /nonexistent --no-create-home "$USER"
fi

systemctl --system daemon-reload >/dev/null
deb-systemd-invoke start jasper >/dev/null

exit 0
