#!/bin/sh

set -e

USER=jasper

if ! getent passwd "$USER" >/dev/null; then
 adduser --quiet --system "$USER"
fi

systemctl --system daemon-reload >/dev/null
#systemctl start gowiki.service >/dev/null 