#!/bin/sh

set -e

USER=jasper

if ! getent passwd "$USER" >/dev/null; then
 adduser --quiet --disabled-login "$USER"
fi

deb-systemd-helper --system daemon-reload >/dev/null
deb-systemd-helper start gowiki.service >/dev/null 